services:
  mariadb:
    image: mariadb:11
    container_name: superstore_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_dw
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/data:Z

volumes:
  db_data: {}
